### ISSUE TITLE
Modern sound card (AC97/HDA) support

### ISSUE THREAD

**Issue by Wengier** [Baron-von-Riedesel/HX#11]
The current HX DOS Extender (2.18) is very powerful, but it seems to support Sound Blaster cards only. On the other hand, there was a HX modification called HX 2.17+ by Ruslan, adding support for modern sound cards such as Intel-HDA, ICH/AC97, VIA82xx, ENS1371/1373, CMI 8338/8738, which apparently makes it even more useful. It is available from the following page:

https://sound-dos.ucoz.ru/load/new_hxdos_extender_2_17/1-1-0-8

Could you please add support for these sound cards in the official HX DOS Extender too? Thank you very much!

**Comment by Baron-von-Riedesel** [comment]
Would be nice, indeed, to add support for Intel HDA. However, the author hasn't released the source, AFAICS. I once "talked" with him, but he "disappeared" after introduction. :))

**Comment by Baron-von-Riedesel** [comment]
As a first step, I played with HDA to see how stable this might get in DOS.

See [https://github.com/Baron-von-Riedesel/HDAutils](url) 

So far, it works pretty good, but not on all machines ...

**Comment by andrewbird** [comment]
The link above is broken...

**Comment by Baron-von-Riedesel** [comment]
The link above is broken...

Thanks. I really wonder why they do such strange post-processing of urls. Should be fairly simple, IMO ...

**Comment by Wengier** [comment]
@Baron-von-Riedesel Thanks a lot! I could run the player (either from the downloads or compile by myself). For now I have not yet been able to get any sound from my computers yet (although MPXPLAY do not support all of them either), but I am sure it will work on other computers at this time. Thanks again for the effort!

**Comment by Baron-von-Riedesel** [comment]
@Wengier: thanks for the feedback. The current version of hdaplay indeed works on all computers with hda that I tried so far.

The next steps might be :
- make a player that uses interrupts (the current player just makes the dma engine dump the whole file).
- add the code to HX winmm.

The only problem is that I need to - at least partially - understand the sb16 code written 15 years ago.

**Comment by Wengier** [comment]
@Baron-von-Riedesel If you have VMware Workstation (I am using 15.1.0), you can ask it to emulate a HDA sound card by setting the following in the VMX config file of a virtual machine:

```
"sound.virtualDev = "hdaudio"
```

With this setting MPXPLAY 1.65 will be able to play the WAV file I tried. But with HDAPLAY and the same WAV file I got the following screen and the VM freezes:

![image](https://user-images.githubusercontent.com/8216923/106683076-d00b5900-6591-11eb-8151-f7a495136eb4.png)

It is great to hear your next plans though. I hope it becomes better and better.

**Comment by Baron-von-Riedesel** [comment]
>  the VM freezes (with no sound):
I guess it doesn't "freeze" (pressing ctrl-alt-del should make hdpmi terminate the program), it just waits pretty long.

Btw, I won't care much about errors reports in virtual environments. The only emulators that I use are dosemu2 and qemu. Dosemu has no support for PCI (so HDA is out of the question) and qemu's DOS emulation is still terrible.

**Comment by Wengier** [comment]
@Baron-von-Riedesel Yes, pressing Ctrl-Alt-Del can make HDPMI terminate the program as you said, although there is still no sound in such case. But thanks for the hint.

I reported the error in the virtual environment simply because it is reproduceable and verifiable by everyone who has the software, and fix it if possible. If I reported the error occurred in the real machine(s) I tested, then I believe almost nobody but myself can actually check and fix the issue.

**Comment by Baron-von-Riedesel** [comment]
> If I reported the error occurred in the real machine(s) I tested, then I believe almost nobody but myself can actually check and fix the issue.

That's too pessimistic. It's easy to add displays into the 2 HDA tools that are supplied ( and they are very easy to assemble ), so one can find out where they don't behave as expected - you just have to be able to make a screen shot.

The emulators just emulate the hardware not good enough.

**Comment by Wengier** [comment]
@Baron-von-Riedesel I see. So I am posting the results I got with two laptops having HDA sound cards:

Laptop 1:

```
A:\>HDAPLAY CHIMES.WAV
Channels=1
Samples/Second=22050
Bits/Sample=8
data subchunk size=15876
EMB physical address=8cfff000, used for CORB, RIRB and BDL
EMB physical address=113c00, used for samples

HDA Base Address=0xb3310000

CORB/RIRB before init
CORB address=0x8cfff000, WP=0, RP=0
CORB status=0x0, control=0x0 - DMA stopped
RIRB address=0x8cfff400, WP=0, RIC=0
RIRB status=0x0, control=0x0 - DMA stopped

CORB/RIRB after init
CORB address=0x8cfff000, WP=0, RP=0
CORB status=0x0, control=0x2 - DMA running
RIRB address=0x8cfff400, WP=0, RIC=1
RIRB status=0x0, control=0x2 - DMA running

hdpmi: app terminated by user request
```

Laptop 2:

```
C:\>HDAPLAY.EXE CHIMES.WAV
Channels=1
Samples/Second=22050
Bits/Sample=8
data subchunk size=15876
EMB physical address=2ffc000, used for CORB, RIRB and BDL
EMB physical address=2ffd000, used for samples

HDA Base Address=0xd0400000

CORB/RIRB before init
CORB address=0x2ffc000, WP=0, RP=0
CORB status=0x0, control=0x0 - DMA stopped
RIRB address=0x2ffc400, WP=0, RIC=0
RIRB status=0x1, control=0x0 - DMA stopped

CORB/RIRB after init
CORB address=0x2ffc000, WP=0, RP=0
CORB status=0x0, control=0x2 - DMA running
RIRB address=0x2ffc400, WP=0, RIC=1
RIRB status=0x1, control=0x2 - DMA running

hdpmi: app terminated by user request
```

In both cases I had to press the Ctrl+Alt+Del key to force stop the player (no sound ever came out).

**Comment by Baron-von-Riedesel** [comment]
It looks like there's a general problem talking to the codec.

I've updated hdautils, improved the debug displays concerning codec communication.
You'll have to get the modified source, modify hdaplay.asm ( change "?LOGCODEC equ 0" to "?LOGCODEC equ 1" ), and run mhdaplay.bat to create the binary.
The modification won't make the program work, but it should tell if the hda controller at least has been able to sent the command over the "link" to the codec. 

I've tested the utilities with one notebook only, and it worked, although the communication with the codec was suspiciously "slow", so there definitely are problems.

**Comment by Baron-von-Riedesel** [comment]
When doing tests on notebooks one should disable any "dosidle" utilities in config.sys. That's because both hdautils have a "wait" function implemented that calls int 2Fh, ax=1680h and expects al=0 on return if the call has been "handled" - something that not all dosidle tools will do. The result may be that the "wait" lasts 65536 * 55ms = 3600 seconds.

**Comment by Wengier** [comment]
@Baron-von-Riedesel Since the latest commit adds a -s option, I decide to use the latest version for the report. I changed ```?LOGCODEC equ 0``` to ```?LOGCODEC equ 1``` in hdaplay.asm and built the binary myself, but when I tried it on my two laptops all I got was the following:

```
Channels=1
Samples/Second=22050
Bits/Sample=8
Data subchunk size=15876
EMB physical address=8cfff000, used for CORB, RIRB and BDL
EMB physical address=113c00, used for samples
HDA Base Address=0xb3310000
sendcmd: cmd f0004 send, waiting for response
```

The results from the two laptops are same except for actual addresses. It hang here, and pressing Ctrl+Alt+Del would immediately restart the computer, so I could not save the above messages automatically and had to write down the messages manually. I also tried to disable all utilities except for the required HIMEM.SYS, but got the same results.

**Comment by Baron-von-Riedesel** [comment]
> and pressing Ctrl+Alt+Del would immediately restart the computer

That's very strange and shouldn't happen at all ???

> I also tried to disable all utilities except 

that's no longer necessary because I removed the int 2fh, ax=1680h call during waits.

Generally, I tested the tools on 10 machines ( 8 "desktops", 2 notebooks ) - and they run on all of them. So I'm pretty sure the hda driver will finally work on most machines - that's sufficient to implement it in HX.

If you're still interested to make your notebooks work with this you could perhaps try to send a NULL command (writing 00000000 into the CORB buffer) directly after initialization - I vaguely remember having read such a hint in the osdev forum ...

**Comment by Wengier** [comment]
> That's very strange and shouldn't happen at all ???

The previous HDAPLAY.EXE binary I built was not correctly patched by PATCHPE, so I used DPMILD32.EXE 3.9 to load HDAPLAY.EXE and pressing Ctrl+Alt+Del would immediately restart the computer. If it is patched and I load it directly then pressing Ctrl+Alt+Del will not restart the computer, unless EMM386.EXE is loaded in CONFIG.SUS with ALTBOOT option. But I would get the same output when trying to play a WAV file in any case.

> Generally, I tested the tools on 10 machines ( 8 "desktops", 2 notebooks )

Looks like you tested the tools mostly on desktop computers. I had some “desktops” too but these are almost all old computers without HDA sound cards. On the other hand, more recent computers I have (with HDA sound cards) are almost all laptops.

> If you're still interested to make your notebooks work with this you could perhaps try to send a NULL command (writing 00000000 into the CORB buffer) directly after initialization

What statement(s) and where exactly should add to HDAPLAY.asm? Sorry but I am definitely not a master in the assembly language.

**Comment by Baron-von-Riedesel** [comment]
> What statement(s) and where exactly should I add to HDAPLAY.asm? 

Sending the NULL verb (or command) has been added to the source, optionally ( change line to ?SENDNULL equ 1 ).
The verb's mentioned in the HDA specification, it can always be sent to the codec (which is the real audio "chip") and won't get a response. Why it should be necessary isn't mentioned, however, so I'm a bit sceptical that it'll change much.

**Comment by Wengier** [comment]
Thanks. I have tried the latest HDAPLAY.asm with ```?LOGCODEC equ 1``` and ```?SENDNULL equ 1``` on the two laptops I tested earlier, but there is indeed no change - the last line is still that "waiting for response" but there will never be a response. I also attached the hdaplay.exe binary I compiled myself for the tests.

* [hdaplay.zip](https://github.com/Baron-von-Riedesel/HX/files/5975653/hdaplay.zip)

**Comment by Wengier** [comment]
@Baron-von-Riedesel Are there any other suggestions on how to fix this issue?

P.S. I have been busy with DOSBox-X developments and other things, which was why it may take some time for me to post back. But I am certainly glad to see such developments in the DOS world. Let me know if there is any way to solve this. Thanks.

**Comment by Baron-von-Riedesel** [comment]
> Let me know if there is any way to solve this. 

Things that you might still try are:

1. run tool SetMtrr (see my repositories) and post the results. The HDA register map must be uncachable.

2. does mpxplay emit sound on your notebooks? The HD audio specification is generic, but it's not guaranteed that to activate it isn't vendor-specific. If mpxplay works, however, this is most likely not the problem.

**Comment by Baron-von-Riedesel** [comment]
Finally I was able to make hdaplay run in Qemu. Inspecting the qemu source gave a hint how it might work. But the adjustments that were needed don't comply to the specs - I won't implement it that way. The hdaplay utility uses CORB/RIRP, but no interrupts - that's apparently a configuration that qemu isn't prepared for.

Mpxplay is no big help - it uses so-called "direct" commands - these are optional, according to Intel, so this is no path for me.

**Comment by Wengier** [comment]
@Baron-von-Riedesel There are a few options for the SetMtrr tool, and I tried with "setmtrr -s". But running it beforehand does not appear to make a difference in these cases.

Great to hear that you were able to make it run in Qemu and also found how MPXPLAY improves the handling. I agree that there may be no need to support it in the default setting if they are optional or don't comply to the specs, but how about make it an option (e.g ```?QEMUCOMP equ 1``` / ```?USEDIRECT equ 1```) for people who want to use HDAPLAY in these configurations?

**Comment by hjnijlunsing** [comment]
> https://sound-dos.ucoz.ru/load/new_hxdos_extender_2_17/1-1-0-8

Seems the source can be found here: https://sound-dos.ucoz.ru/load/source_code_sound_lib/1-1-0-7

Kr

**Comment by guilt** [comment]
There is a fork of HX now and SBEmu seems to work with it. Any chances these port trapping changes etc. Will get merged into HX?

https://github.com/crazii/SBEMU

**Comment by Baron-von-Riedesel** [comment]
> Any chances that these fixes/diffs changes get merged into HX?

No. There are no "fixes" in crazii's fork. The current HX has a ( documented ) port trapping API implemented, but this was finished in 01/2023, after crazii forked hdpmi32 (in 12/2022). The two versions are not compatible.

**Comment by crazii** [comment]
There're fixed for MDK's keyboard if I remember.

**Comment by volkertb** [comment]
@Baron-von-Riedesel If the incompatibility of the port-trapping APIs between @crazii's HDPMI32i fork and the upstream version is the raison d'être of VSBHDA, and @crazii has no desire to continue maintaining an incompatible fork, can we maybe work together to reconcile this? If you can help us "port" SBEMU to your upstream port-trapping API, then you won't have to maintain VSBHDA anymore, and he won't have to maintain that HDPMI32i fork anymore.

And even if you wish to continue working on VSBHDA, which is also cool, it would still be beneficial to have bot VSBHDA and SBEMU work with the maintained "blessed" API.

Ultimately, this all seems more like a misunderstanding and sad timing more than anything else.

I think it's safe to say that there is really a consensus behind getting SBEMU to just work with the upstream API.

We appreciate any help you can give us with this. Thanks!

Best wishes for 2024 to all of you, by the way. :star2:

**Comment by Baron-von-Riedesel** [comment]
> If the incompatibility of the port-trapping APIs between @crazii's HDPMI32i fork ...

It's actually a bit worse: once SBEMU is loaded, all the protected-mode programs that use the HX Win32 emulation layer ( i.e. JWasm ) crash immediately after launch. 

Of course I'm willing to help adapt SBEMU to the API implemented in hdpmi; however, currently I'm unable to spend much time for programming...

**Comment by volkertb** [comment]
Perhaps you can provide some guidance and pointers? Or maybe we can help you document the API?

**Comment by Baron-von-Riedesel** [comment]
> Or maybe we can help you document the API?

It has already been documented - see [HX/src/HDPMI/DPMIAPI.TXT](url)

**Comment by guilt** [comment]
@crazii Do we know why this happens? Can this issue be addressed? Is it a hard issue to fix? As few others have pointed out, this may indeed help upstreaming the code.

> It's actually a bit worse: once SBEMU is loaded, all the protected-mode programs that use the HX Win32 emulation layer ( i.e. JWasm ) crash immediately after launch.

**Comment by volkertb** [comment]
> > Or maybe we can help you document the API?
> 
> It has already been documented - see https://github.com/Baron-von-Riedesel/HX/blob/master/Src/HDPMI/HDPMIAPI.TXT

@crazii (SBEMU) and @bjt42 (SoftMPU), is this API and documentation sufficient for both of you to work with?

**Comment by volkertb** [comment]
@pdewacht do you think you could also leverage this API in HDPMI21i to add support for protected-mode DOS games to  [ADLiPT](https://github.com/pdewacht/adlipt)?

@vincentbernat bringing this to your attention as well, since you might also find this interesting, considering the retro DOS sound projects you've worked on.

**Comment by crazii** [comment]
> @crazii Do we know why this happens? Can this issue be addressed? Is it a hard issue to fix? As few others have pointed out, this may indeed help upstreaming the code.
> 
> > It's actually a bit worse: once SBEMU is loaded, all the protected-mode programs that use the HX Win32 emulation layer ( i.e. JWasm ) crash immediately after launch.

No, But I can test why it happens, it could be fixed.
