### ISSUE TITLE
Complete source migration?

### ISSUE THREAD

**Issue by Ringdingcoder** [Baron-von-Riedesel/HX#12]
What are your plans for moving over all the remaining content that was in HX 2.17 over to this repo? In particular, I'm waiting for the OS/2 16-bit stuff.

**Comment by Baron-von-Riedesel** [comment]
Is there really anything useful missing? If you have something concrete I'll have a closer look.

**Comment by Ringdingcoder** [comment]
DOSXXX (from HXD16)!

**Comment by Baron-von-Riedesel** [comment]
Ok. I'll see if that code may be (re)published. IIRC I removed the source in v2.17, regarding it obsolete.

**Comment by Ringdingcoder** [comment]
I noticed that you added `DOSXXX`, and I am very happy about it. However, I have no idea how `kernel16.lib` was built, which is required for `DOSCALLS`. I can take the one from the `HXD16217.zip` package, but also in the 2.17 sources, I cannot find anything that builds it.

I can see that it is only an import library for a DLL, so it would not be that hard to re-create. I’m just surprised that there is nothing in the sources (that I can find, at least). I don’t remember how to build a Win16 implib, though. I guess studying some old manuals is in order.

**Comment by Ringdingcoder** [comment]
Ok, I found out how it could have been created: Using Microsoft’s `implib` tool on `krnl286.exe`. This produces a lot more entries than the ones present in kernel16.lib, but they can easily be picked apart and recombined to create a slimmer library.

**Comment by Baron-von-Riedesel** [comment]
I guess I also used MS implib, using dpmild16.exe as source - this loader emulates a few win16 kernel functions.

**Comment by Ringdingcoder** [comment]
By chance I just found out that wlib can create import libraries from textual specifications. I stumbled over this in the `open-watcom-v2` build:

`bwlib -b-n-pa -s-t-zld -ii -io test.lib @file.lbc`

Where `file.lbc` contains lines like so:
```
++SETRELABS.GDI.5
```
