### ISSUE TITLE
Regression in HDPMI32 v2.19 pre7, a crash

### ISSUE THREAD

**Issue by VaKonS** [Baron-von-Riedesel/HX#18]
Hello and thank you for your project!

I'm trying to use HDPMI32 as a replacement for CWSDPMI.
Until version 2.19 pre7 it worked fine, but with latest pre-release the extender crashes with "page fault" error.

The problem is reproducible in DosBox and in regular DOS (able to handle 64 Mb of memory – 7.1, for example).
Steps to reproduce:
- unpack the attached archive: [hdpmi32_219p6p7.zip](https://github.com/Baron-von-Riedesel/HX/files/6992804/hdpmi32_219p6p7.zip), 348 599 bytes, md5:
794e77d8315581e504e37b1dac79e9b3 *hdpmi32_219p6p7.zip
- give DosBox 64 Mb of XMS memory;
- run "67.bat".

Test will first try to pack a file under hdpmi32 v2.19 pre6 and then will crash under hdpmi32 v2.19 pre7.

Again, thank you very much!
With best regards, Valentine.

**Comment by Baron-von-Riedesel** [comment]
I tried 67.bat twice, under real DOS 7.1 and DOSbox (v0.74, memsize=64), and both tries worked ok without crash.

I didn't try the latest DOSbox, it was a Win32 executable from 2010, though.

**Comment by VaKonS** [comment]
Thank you, if it does not crash, it can not be fixed, I guess, I'll close the issue then.

If it may give any clues, however, I've tried the test on 3 DosBoxes – mainline 0.74 (of 2010), [dosbox-x](https://github.com/joncampbell123/dosbox-x) 0.83.16 (latest at the moment) and even "Magic DosBox" for Android – on all of them I'm getting stable crash on 2.19 pre7 with exactly the same registers dump, even on Android:

process 2 get hardware fault 14 (page fault) at 927CE
writing core file
Kernel fault at AF 110F7
EAX=000000D7 EBX=00002000 ECX=00000800 EDX=00000000
EBP=0000F7F0 ESP=0000F7E4  ESI=01A92000 EDI=00031CA4
CS=00AF DS=00D7 ES=00B7 SS=00B7

Here are the HDPMI32 core dumps and DosBox configs: [crash_dumps.zip](https://github.com/Baron-von-Riedesel/HX/files/7008704/crash_dumps.zip), 121 077 bytes.

In any case, thank you very much!

**Comment by Baron-von-Riedesel** [comment]
I had setting "xms=false" in my dosbox.conf file.
After changing it to "xms=true", the crash does appear.
Will look into it later.

**Comment by Baron-von-Riedesel** [comment]
Ok, bug is ( hopefully ) fixed with latest commit.
Will create a new prerelease in a few days.

**Comment by VaKonS** [comment]
I found wmake and compiled the fix (with EditPE from HXDEV 2.19 pre6). Tested in DosBoxes and in DOS, can confirm that HDPMI32 works!
Vielen Dank! :)
