### ISSUE TITLE
LPMS is only used once

### ISSUE THREAD

**Issue by jwt27** [Baron-von-Riedesel/HX#20]
Hi @Baron-von-Riedesel,

I believe I found a bug in HDPMI. In the following code (routine `rpmstacke`):

https://github.com/Baron-von-Riedesel/HX/blob/488d6f28e3bfa919be24a82c88c2f808e74184cc/Src/HDPMI/HDPMI.ASM#L2194-L2200

The incoming `esp` is compared to the end of the LPMS to determine if that is
still in use.  However, the full exception frame is never popped off, so this
check always fails.

As a result, only the very first exception uses the LPMS, and then all
subsequent exceptions and interrupts run on the client stack.

**Comment by Baron-von-Riedesel** [comment]
> As a result, only the very first exception uses the LPMS, and then all
> subsequent exceptions and interrupts run on the client stack.

That's very unlikely and, btw., very easy to test on your own.
Generally, this crucial part of hdpmi is pretty thoroughly tested: that doesn't mean it's definitely bug-free, but such an obvious bug ... no!

**Comment by jwt27** [comment]
Well, that is what I'm seeing though.  Try it for yourself.
The first exception gives me `ss=0087`, then the next one I get `ss=00b7` which is my client SS.

**Comment by Baron-von-Riedesel** [comment]
here's a test program, may be used with hdpmi32 or cwsdpmi:

'''
;--- catch exc 0Dh

		.386
		.MODEL FLAT, stdcall
		option casemap:none

CStr macro text:vararg
local sym
	.const
sym db text,0
	.code
	exitm <offset sym>
endm

	.data

dsreg dd 0

	.CODE

	include printf.inc

myexc proc
	mov ds,[dsreg]
	invoke printf, CStr("inside exception handler init, ss=%X",10), ss
	mov  [esp+3*4],offset caught
	retf
myexc endp

main proc c

	mov dsreg,ds
	invoke printf, CStr("init, ss:esp=%X:%X",10), ss, esp
	mov ax,0202h
	mov bl,0Dh
	int 31h
	push ecx
	push edx

	mov ecx, cs
	mov edx, offset myexc
	mov ax,0203h
	int 31h
	mov esi,5
nexttry:
	mov eax,cs
	mov ss,eax
caught::
	invoke printf, CStr("exception 0Eh catched and cured, ss=%X",10), ss
	dec esi
	jnz nexttry

	pop edx
	pop ecx
	mov bl,0Dh
	mov ax,0203h
	int 31h

	invoke printf, CStr("done, ss:esp=%X:%X",10), ss, esp

	ret
main endp

start:
	call main
	mov ax,4c00h
	int 21h

	END start
'''

and here is what it displays:

'''
init, ss:esp=b7:11bfc4
inside exception handler init, ss=87
exception 0Eh catched and cured, ss=b7
inside exception handler init, ss=87
exception 0Eh catched and cured, ss=b7
inside exception handler init, ss=87
exception 0Eh catched and cured, ss=b7
inside exception handler init, ss=87
exception 0Eh catched and cured, ss=b7
inside exception handler init, ss=87
exception 0Eh catched and cured, ss=b7
done, ss:esp=b7:11bfc4'''

**Comment by Baron-von-Riedesel** [comment]
> The longer stack frame breaks it.

Confirmed.

> This probably won't have a straightforward solution since rpmstacke needs to know if the handler was registered with 0203 or 

It's actually not really complicated, since the host can easily distinguish the variants. That stack compare code in rmpstacke isn't truly necessary. The fix is already implemented ( not on github, though ), but requires some tests, of course.

**Comment by jwt27** [comment]
I see you committed a fix. nice.  I thought you would change `LPMSused` to a counter, but this works just as well.

This also fixes the case where an exception handler copies the frame and returns on a different stack.  I think that is technically legal.  With the previous implementation that would also permanently block the LPMS.

**Comment by Baron-von-Riedesel** [comment]
> This also fixes the case where an exception handler copies the frame and returns on a different stack.

That may be an interesting side effect, but I haven't thought of that in the least. Might be interesting to test on what dpmi host such code would work.

Btw., there's now a draft v2.19 available. If no serious error pops up in the next weeks, it will become the final v2.19.

**Comment by jwt27** [comment]
> That may be an interesting side effect, but I haven't thought of that in the least. Might be interesting to test on what dpmi host such code would work.

I believe cwsdpmi handles it correctly, and I thought hdpmi did too, but I wasn't aware of this LPMS issue previously.  It will crash on dosemu2.
I used to do this in my exception code because it's easier to access the frame from a flat address space in C++, and it avoids copying the whole thing twice.

**Comment by jwt27** [comment]
I believe I'm still seeing cases where the exception ends up on the client stack.  Weirdly this seems to happen only when I run my program first with cwsdpmi, and then again with hdpmi.  Really I'm not sure what's going on, it's very hard to debug.
