### ISSUE TITLE
How to disable the special key Ctrl + C?

### ISSUE THREAD

**Issue by hlizard** [Baron-von-Riedesel/HX#22]
I use hx-dos to execute dosbox-x under MS-DOS, but when I press Ctrl + C(or Ctrl+Break), dosbox-x will be terminated directly. Do hx-dos have any settings for this?

https://github.com/joncampbell123/dosbox-x/issues/3439

**Comment by Baron-von-Riedesel** [comment]
No.
Isn't this just a problem of setting BREAK ON/OFF on the command line?

**Comment by hlizard** [comment]
You taught me a basic DOS command. Thank you. That's what I want.
