### ISSUE TITLE
How HX DOS Extender can be detected?

### ISSUE THREAD

**Issue by jmalak** [Baron-von-Riedesel/HX#25]
How I can detect if application is running with HX DOS Extender?

**Comment by Baron-von-Riedesel** [comment]
In  hdpmi.txt, Int 31h, ax=401h is mentioned as the preferred method to detect hdpmi - and that's virtually also the method to detect hx-dos extender.

Since v3.20 of hdpmi, there's also an API - the entry point is received via int 2Fh, ax=168Ah ( protected-mode only ).

**Comment by jmalak** [comment]
Yes, it is detection of HDPMI.
I suppose that HX DOS Extender can run with other DPMI servers or is it limited to use only HDPMI?

**Comment by Baron-von-Riedesel** [comment]
> I suppose that HX DOS Extender can run with other DPMI servers or is it limited to use only HDPMI?

It needs a host with DOS API translation - hdpmi, dosemu, Windows DOS boxes...

For a Win32 program, there's the possibility to detect the HX Win32 emulation dll dkrnl32.dll: GetProcAddress( hKernel32, "GetDKrnl32Version" ). It's described in dkrnl32.txt.

**Comment by jmalak** [comment]
OK, Thanks.
