### ISSUE TITLE
HDPMI32.EXE ver 2.18 introduced a problem with Quake2 under MS-DOS 6.22

### ISSUE THREAD

**Issue by xrayer** [Baron-von-Riedesel/HX#3]
Hi, I just tested update to HXRT 2.18 and found that new version of HDPMI32.EXE 2.18 cause error when trying to run Quake2:
it switch to graphics mode and displays:
recursive shutdown
Couldn't load pics/colormap.pcx [OK]
This is error from Quake2 but why? When I replaced 1 file HDPMI32.EXE 2.18 by ver 2.17 it works OK. I also found, that under MS-DOS 7.1 it works even with HDPMI32.EXE 2.18. I guess something might be broken in new version...

**Comment by Baron-von-Riedesel** [comment]
What DOS version did you use when the error occured?

**Comment by xrayer** [comment]
I have this problem when run on MS-DOS 6.22.

**Comment by Baron-von-Riedesel** [comment]
I confirm problems of hdpmi v3.18 with Q2 in MS-DOS 6.22. Just to be sure we're talking about the same problem: does the error disappear if DOSLFN is loaded?

**Comment by Baron-von-Riedesel** [comment]
should be fixed now.
