### ISSUE TITLE
Included setmzhdr does not work on Windows

### ISSUE THREAD

**Issue by Ringdingcoder** [Baron-von-Riedesel/HX#30]
The `setmzhdr` utility that is used for producing `hdpmi16.bin` fails with "setmzhdr: write error" when run on Windows XP. The same does not happen with the DOS-based version of this tool that’s included in `HXSRC217.zip`.

**Comment by Baron-von-Riedesel** [comment]
just tried in Win XP SP3, got no errors ( "nmake -f hdpmi16s.mak" ).
I modified setmzhdr.asm, so it will display errno now if a read or write error occurs.

**Comment by Ringdingcoder** [comment]
> I linked against libc32s.lib from HX 2.17.

Or rather, against the entire `LIB` directory from HX 2.17. I had my `LIB` environment variable pointed there. So it might have been caused by any one of the binaries in there.
