### ISSUE TITLE
VDS (INT 4b) translation of lock/unlock DMA buffer

### ISSUE THREAD

**Issue by a11599** [Baron-von-Riedesel/HX#32]
I'm writing a minimal protected mode environment and try to make sense of VDS. I want reliable ISA DMA transfers under DPMI, too (the rest is fine, since my host has control over paging). I'm trying to make sense of VDS and VDS service translation in DOS extenders. I probably miss something, but I can't understand how VDS lock/unlock DMA buffer region (0x03/0x04) service translation is supposed to fulfill the purpose of the original VDS service.

To my understanding, these are supposed to adjust page tables of a given linear address so that the physical addresses behind them become contiguous and suitable for DMA transfers. VDS services can either be provided by an EMS manager/VCPI host such as EMM386 for real/V86 mode DOS applications or by a DPMI host for real/V86 (?) and protected mode clients (the only existing VDS documentation by MS is very vague on this).

When true VDS (not just a translated service, but a full implementation such as the one in Windows) is provided by DPMI, everything is clear and I see how lock/unlock DMA buffer (0x03/0x04) will do that. However, if VDS lock/unlock is simply translated to an EMM/VCPI server using a simulated real/V86 mode call, I fail to see how this is possible. In this case the VDS provider can only alter its own page tables, not HDPMI's (or of any other DPMI hosts that implement only a service translation). The VCPI server's page tables are only synchronized during initial mode switch (VCPI service 0xde01), and even then only up to 4 MB.

Can you please shed some light? Am I missing something?

**Comment by Baron-von-Riedesel** [comment]
> To my understanding, these are supposed to adjust page tables of a given linear address so that the physical addresses behind them become contiguous and suitable for DMA transfers. 

IIRC, this is an optional feature only. "Usually" the lock has the result that if the region in question isn't contiguous, the "DMA buffer" is used instead.

> In this case the VDS provider can only alter its own page tables, not HDPMI's (or of any other DPMI hosts that implement only a service translation). 

Absolutely true. VDS translation for 03/04 is meant for "DOS memory" only ( address region 0-10ffff ).

HDPMI handles VDS functions 05/06 only. Combined with the DPMI "mapping" functions that should be sufficient.

**Comment by a11599** [comment]
Thanks. In the end I just got away by allocating low memory (below 640K) under DPMI and it seems to work just fine under DOS extenders as well as Win9x DOS boxes. Good enough for me, no hassle with VDS.
