### ISSUE TITLE
Borland 32RTM and HDPMI32

### ISSUE THREAD

**Issue by awik32** [Baron-von-Riedesel/HX#39]
Hi,

I've been  playing around with Borland C compilers, especially versions 4.52 and 5.2.  The 32-bit compiler, BCC32 is of particular interest, so I shall focus on that, but there are several other programs that use the same DOS extender, RTM32.EXE.

BC 4.52 runs under HDPMI32 version 3.17, *if* I set HDPMI=2048.  Meanwhile, BC 5.2 hangs, with no output at all (ie. no errors reported).

With HDPMI 3.20, BC 4.52 immediately reports exception 0D and dumps the registers.  The same happens with BC 5.2.

The compilers are PE-format executables, so they run fine under Win98 (ie. GUI loaded) and with the HX PE loader, probably because in these situations, 32RTM.EXE is bypassed.

For more information on RTM32.EXE in the absence of HX, see: https://www.bttr-software.de/forum/board_entry.php?id=21169

-Albert

**Comment by Baron-von-Riedesel** [comment]
For me, bcc32.exe v4.52 and v5.51 run under ms-dos 7.1 without problems, AFAICS.
However, I usually load hxldr32.exe in config.sys, so these binaries run under HX's Win32 emulation - I guess, 32rtm.exe is not involved then?

So please provide a detailed description how the "crashing" binaries are to be launched.

**Comment by awik32** [comment]
> so these binaries run under HX's Win32 emulation - I guess, 32rtm.exe is not involved then?

That is my understanding yes.  Another situation where 32RTM.EXE is bypassed is when you run a program under a 32-bit Windows environment.  In both these cases, the PE part of the executable is loaded directly without invoking the DOS stub.

> So please provide a detailed description how the "crashing" binaries are to be launched and what memory managers and dpmi hosts are loaded.

In most of my tests, I added the BC "bin" directory to the start of the PATH, with the HX "bin" farther toward the end of the PATH.  I tried BCC32 from both versions (4.52 and 5.2) in a very basic DOS real mode environment, including HIMEM, KEYB, and CMDEDIT.

Then I load HDPMI32, with or without HDPMI=2048.  Then I simply run BCC32.  See my first message above for details, but in short, only the test case consisting of "HDPMI=2048" + HDPMI v3.17 + BC 4.52 works properly.

The DOS version is the one that comes with Win98SE.

I can provide the output of MEM /C if you like.

**Comment by Baron-von-Riedesel** [comment]
I had a deep look into hdpmi's source code. There are indeed a few changes that I can't recall why they were implemented. It's a bit of a mess.

Running 32rtm.exe causes a GPF termination, running code 0F C0 22, which is a "mov cr0, eax".

This instruction is priviledged, but there's an assembly-time switch, ?EMUMOVCR0REG, which, if set to 1, is supposed to emulate this instruction in ring 0. However, this switch is 0, in both hdpmi v3.20 and v3.17. Why v3.17 works is because the switch was implemented buggy, actually allowing that MOV instruction. In v3.20, it works ( as expected, but undocumented ).

For v3.20, things are indeed complicated. The "MOV CR0, <register>" may still work, but only for HDPMI32i AND if HDPMI=2048 is set - obviously I was aware of the problem with 32RTM.EXE, as the comment tells:
 
```
emuspecregmove2:
ife ?EMUMOVCR0REG
 ife ?PMIOPL
	test ss:[bEnvFlags2], ENVF2_CLRHIWORD	; allow "mov cr0, reg" (32RTM.EXE)
	jnz @F
 endif
	mov al,[esi]
	and al,0F8h
	cmp al,0C0h		; mov cr0, reg?
	jz done			; return and do a GPF
@@:
endif
```

That's not all. In v3.19, the "vendor" "VIRTUAL SUPPORT" was removed ( this is documented ). However, without this "vendor" 32RTM thinks that uncommitted memory isn't supported. That's why you have to enable another bit in the HDPMI environment variable - it must be set by "SET HDPMI=2052". Actually, this bit makes HDPMI32i to report it is a DPMI v1.0 host, but apparently 32rtm is happy with it.

**Comment by awik32** [comment]
Thank you for taking the time to investigate.

> running code 0F C0 22, which is a "mov cr0, eax".

I think you mean "0F 22 C0".  That is the code from the dump below.

I tried setting HDPMI=2052 and installing HPDMI32I, but I still get this:
```
Exception 0D
EAX=80000011 EBX=000003F0 ECX=00000F94 EDX=00001261 ESI=000110A9
EDI=000019CF EBP=00000912 ESP=000003EC EFL=00010286 EIP=000018DF
CS=0097 (00010A90,0000FFFF,00FB) SS=009F (00012610,0000FFFF,40F3)
DS=008F (0000FA40,0000FFFF,40F3) ES=00C7 (00111000,1EFFFFFF,C1F3)
FS=0000 (********,********,****) GS=0000 (********,********,****)
LDTR=0038 (FF80F000,00000FFF,0082) TR=0030 (FF8086F0,00003910,008B)
ERRC=0000 (********,********,****) PTE 1. Page LDT=00121467
GDTR=07FF:FF80E000 IDTR=07FF:FF80E800 PTE CR2=00000067
CR0=80000011 CR2=00000000 CR3=00114000 CR4=00000200 TSS:ESP0=00004918
DR0-3=00000000 00000000 00000000 00000000 DR6=FFFF0FF0 DR7=00000400
LPMS Sel=0087(01) RMS=16A5:0200 open RMCBs=0000/0000 ISR=0000
   [EIP]=0F 22 C0 E8 13 FF 2E A1 6D 00 8B 36 
   [ESP]=19CF 0097 F000 F000 EFFF 0000 00B7 0006 
000003FC=0BB3 0FC9 0000 0000 0000 0000 0000 0000 
0000040C=0000 0000 0000 0000 0000 0000 0000 0000 
0000041C=0000 0000 0000 0000 0000 0000 0000 0000 
0000042C=0000 0000 0000 0000 0000 0000 0000 0000 
0000043C=0000 0000 0000 0000 0000 0000 0000 0000 
```

**Comment by Baron-von-Riedesel** [comment]
You're right. I checked the current source, but the change that made hdpmi32i optionally accept "mov cr0, <reg>" was done in 03/2023 only, 2 month after v3.20 was released.

**Comment by awik32** [comment]
Did you edit your reply to include the fact that you made a pre-release?

Before I saw it, I had actually downloaded your git repository and attempted to build.  I was successful in building HDPMI and a few other programs.  The HDPMI32I.EXE I built works as well (perfectly) as 3.17 to run BCC32 4.52.  BCC32 5.2 still hangs without output - do you have any idea(s) on that?

**Comment by Baron-von-Riedesel** [comment]
> Did you edit your reply to include the fact that you made a pre-release?

Yes. After all, it was high time to make a release.

> BCC32 5.2 still hangs without output - do you have any idea(s) on that?

No. According to the English Wikipedia, v5.2 doesn't exist - there's only a v4.52, v4.53, v5.0, v5.01 and v5.02. And finally v5.5 ( which I have ). If I read it correctly, v4.52 was the last version with Powerpack support ( Borland DOS extender ).

**Comment by awik32** [comment]
The PowerPack is not enough to make BC 5.x create 32-bit DOS-extended executables.  This is apparently due to an incompatibility with the 5.x libraries.  However, with the 4.x libraries (ie. option -Lc:\bc45\lib) you can create 32-bit DOS binaries.

**Comment by awik32** [comment]
I just discovered that the TLINK32.EXE that's part of BC 4.52 also hangs without output.

On another note, (a) I added a command line option to HDPMI, and (b) I have trouble building some parts of HX (a missing INCLUDE).  This is off topic in this thread/issue, so should I open a new one or e-mail you directly?

**Comment by Baron-von-Riedesel** [comment]
> I just discovered that the TLINK32.EXE that's part of BC 4.52 also hangs without output.

I tried this with brc32.exe ( using a debug version of hdpmi )- there's also apparently a "hang" - but it seems that it's some rather longish loop that happens inside hdpmi - the "hang" finally ends and the program terminates.

So better wait a few minutes when the "hang" happens to see if there's some continuation - just to ensure that we're talking about the very same bug.

> so should I open a new one or e-mail you directly?

Please open a new issue!

**Comment by awik32** [comment]
The TLINK32.EXE from BC 4.52 runs fine under DPMIONE, so I think it could be made to work with HDPMI32.

BC 5.2, however, seems to be a lost cause.  With DPMIONE I get these errors:
```
32loader error: 'C:\BC5\BIN\BCC32.EXE'
    Invalid import references:
       - module 'KERNEL32.dll' entrypoint 'IsDBCSLeadByteEx'
    Do you want to attempt running this program (Y/N)?
(Load error 84)
```
TLINK32 is even worse:
```
ERROR: The program can not be loaded
32loader error: 'C:\BC5\BIN\TLINK32.EXE'
    Invalid import references:
       - module 'KERNEL32.DLL' entrypoint 'CreateFileW'
       - module 'KERNEL32.DLL' entrypoint 'GetCPInfo'
       - module 'KERNEL32.DLL' entrypoint 'GetDateFormatA'
       - module 'KERNEL32.DLL' entrypoint 'GetFileAttributesW'
       - module 'KERNEL32.DLL' entrypoint 'GetStringTypeW'
       - module 'KERNEL32.DLL' entrypoint 'GetTempFileNameA'
       - module 'KERNEL32.DLL' entrypoint 'GetVersionExA'
    Do you want to attempt running this program (Y/N)?
(Load error 84)
32stub error: The program can not be loaded
```

32RTM is apparently some kind of Windows NT emulator.  Here are some strings I found in it:
```
Borland 32 bit loader / NT console emulation
Gábor Ligeti
Eli Boling, Judy Fitzgerald
Keimpe Bronkhorst, Lori Benner
```

The authors, maybe?

Terminal control codes?
```
[30m$
[31m$
[32m$
[33m$
```

It contains references to several Windows DLLs:
```
KERNEL32.DLL
...
KERNEL32
AllocConsole
Beep
Borland32
CloseHandle
CompareFileTime
ContinueDebugEvent
CopyFileA
CreateConsoleScreenBuffer
CreateDirectoryA
[etc]
```
More:
```
NTDLL.DLL
...
ntdll
longjmp
setjmp
DbgBreakPoint
DbgPrint
NtCurrentTeb
RtlAnsiCharToUnicodeChar
RtlAnsiStringToUnicodeString
RtlExAllocateHeap
RtlExFreeHeap
RtlExReAllocateHeap
RtlExSizeHeap
RtlUnicodeStringToAnsiString
RtlUnwind
USER32.DLL
...
CharLowerA
CharLowerBuffA
CharNextA
CharPrevA
```
Apparently it contains embedded Win32 emulation modules:
```
03-16-95 11:14:49 32LOADER - NT emulation module KERNEL32
03-16-95 11:14:49 32LOADER - NT emulation module NTDLL
03-16-95 11:14:50 32LOADER - NT emulation module USER32
```

I'm beginning to think that it makes more sense to run these programs with the help of HX's win32 emulation.

**Comment by awik32** [comment]
> > I just discovered that the TLINK32.EXE that's part of BC 4.52 also hangs without output.
> 
> I tried this with brc32.exe ( using a debug version of hdpmi )- there's also apparently a "hang" - but it seems that it's some rather longish loop that happens inside hdpmi - the "hang" finally ends and the program terminates.
> 
> So better wait a few minutes when the "hang" happens to see if there's some continuation - just to ensure that we're talking about the very same bug.

You are right.  The program (TLINK32) hangs for a few minutes and then resumes execution, hangs again for a shorter time, and finally terminates normally (if you can call that normal!).

**Comment by Baron-von-Riedesel** [comment]
> The program (TLINK32) hangs for a few minutes and then resumes execution, 

That bug should be fixed now.
