### ISSUE TITLE
Open Watcom v2 Fork latest binary build crashed

### ISSUE THREAD

**Issue by j123123** [Baron-von-Riedesel/HX#4]
https://github.com/open-watcom/open-watcom-v2
Watcom NT compiler ``cl`` crashes under HXLDR32
![dmp](https://user-images.githubusercontent.com/4210789/46491736-33dfb480-c814-11e8-83c7-2c2fe7f0eb6e.png)
```
Exception 0D
EAX=003A0002 EBX=003A485F ECX=00000004 EDX=00003B08 ESI=0000485F
EDI=00004A72 EBP=003A4BB4 ESP=003A4776 EFL=00013246 EIP=00000B94
CS=0097 (00111000,000058CF,00FB) SS=00C7 (00000000,FFFFFFFF,CFF3)
DS=008F (00111000,000058CF,40F3) ES=008F (00111000,000058CF,40F3)
FS=0107 (002A3000,00000FFF,00F3) GS=0000 (********,********,****)
LDTR=0038 (FF80F000,00000FFF,0082) TR=0030 (0001F090,00000067,008B)
ERRC=0114 (********,********,****) PTE 1. Page LDT=00159467
GDTR=07FF:FF80E000 IDTR=07FF:FF80E800 PTE CR2=00000067
CR0=E0000033 CR2=00000000 CR3=00149000 CR4=00000200 TSS:ESP0=00002F78
DR0-3=00000000 00000000 00000000 00000000 DR6=FFFF0FF0 DR7=00000400
LPMS Sel=0087(01) RMS=2188:0200 open RMCBs=0000/0000 ISR=0000
   [EIP]=8E 06 54 47 E8 07 FF 72 03 E8 66 FF 
   [ESP]=0CD3 1AC4 048F 4ACF 003A 4BE4 003A 4B00 
003A4786=0000 4B6C 003A 48B4 003A 00C7 00C7 70BC 
003A4796=003C 00BF 0000 3246 0000 0107 003C 7D80 
003A47A6=003D 0000 0000 0044 0000 3A44 005C 27DC 
003A47B6=003D 4820 003A E962 0028 2808 003D 0044 
003A47C6=0000 0000 0000 0000 0000 0000 0000 0000 
```

**Comment by j123123** [comment]
Tested on:
```
                        Bochs x86 Emulator 2.6
            Built from SVN snapshot on September 2nd, 2012
```
Defauit Bochs package from Ubuntu 16.04.5 LTS

**Comment by Baron-von-Riedesel** [comment]
I can see from the dump that it crashes in 16-bit code, it's in DPMILD32.EXE:

`00000B91                        nosysdir:
                                endif
00000B91  BA0005                	mov dx, offset szPathConst	;variable "PATH="
                                if 0
                                else
00000B94  8E061400              	mov es, [wCurPSP]
00000B98  E807FF                	call GetEnvironmentVariable  ;DI=^Path
                                endif
00000B9B  7203                  	jc exit
`

**Comment by j123123** [comment]
Hmm, maybe this is FreeDOS issue? Can you check CL.EXE on FreeDOS 1.2 on real hardware?

**Comment by Baron-von-Riedesel** [comment]
Didn't check on real HW, but run it under FreeDOS 1.2 under VirtualBox and got the very same error.
So it might be a FD issue.
Btw, .the error does not occur if the compile & link step are launched separately (with "cl -c hello.c" and then "link hello.obj".

**Comment by Baron-von-Riedesel** [comment]
The error has nothing to do with FD. It's an error in HX's program loader when DPMILDR=8 isn't set. Has been fixed.
