### ISSUE TITLE
HX does not work well with Borland C++ on DOSBOX-X

### ISSUE THREAD

**Issue by guilt** [Baron-von-Riedesel/HX#48]
Hi,

When HDPMI32 is loaded, BCC freezes for me; Been trying this on DOSBOX-X a lot and have no way to run 
it correctly for me. Plus, newer versions than 2.16 do not load the Microsoft C++ nor OpenWatcom compilers correctly.

If you want a fully repro-use case, see https://github.com/guilt/DOS

**Comment by Baron-von-Riedesel** [comment]
> When HDPMI32 is loaded, BCC freezes for me; 

it doesn't freeze for me; instead, it exits with "cannot initialize". I guess that's because bcc.exe is a 16-bit dpmi application. To make it run while HDPMI32 is loaded, you have to load HDPMI16 as well.

**Comment by guilt** [comment]
Adding `HDPMI16 -r` fixed that for me. Thank you.
