### ISSUE TITLE
How critical sti before iret in hw interrupt handler is?

### ISSUE THREAD

**Issue by MrMadguy64** [Baron-von-Riedesel/HX#49]
I hook Irq 1 completely in my project. I.e. old handler isn't called. I've forgotten to add sti before iret, as demanded by DPMI standard. Standard says, that I have to do it, because iret doesn't enable interrupt flag, so I need to do it manually, otherwise hardware interrupts would stay disabled. But everything works properly. At least in DOSBox and QEMU (both MS-DOS and FreeDOS). Is it critical to add sti before iret? Standard says, that sti call can be slow due to being emulated by DPMI host. Would there be any side effects, if I wouldn't add it? I just can't explain, why it works. May be you know? May be interrupts are reenabled by some HDPMI handler, so I lose all Irq 1s before some other hw interrupt fires?

**Comment by Baron-von-Riedesel** [comment]
It depends on IOPL. The standard HDPMI runs clients with IOPL 3 - in this case the flags restored by IRET will also restore the interrupt flag. However, the HDPMI variants with 'i' suffix run clients with IOPL 0 - in that case the IRET won't restore the interrupt flag - it remains 0 ( interrupts disabled ). Hence the STI should be necessary here.

It's one of the problems of the Rational DOS extender ( DOS4G/W ) - the STI is often missing. That may cause "freezes" if such programs run in a Windows DOS-Box ( with IOPL = 0 ).

**Comment by MrMadguy64** [comment]
Ok, I've added STI anyway.

Related question: what is the best way to handle idling? I.e. I don't want to use loop while waiting for next hw interrupt to happen. What should I do? HLT? Is HLT trapped by DPMI host the same way, CLI and STI are trapped? Or may be I should use Int 2Fh, 1680h? As I see, 1680h isn't handled by HDPMI. It's routed to real mode. I need universal solution, that would be suitable for both raw DOS and Windows DOSBox.

**Comment by Baron-von-Riedesel** [comment]
> Is HLT trapped by DPMI host the same way,

Usually not - but hdpmi does; not really recommended to use it, though.

> Or may be I should use Int 2Fh, 1680h? As I see, 1680h isn't handled by HDPMI. It's routed to real mode.

Well, yes, of course - HDPMI simply doesn't know what to do instead.

**Comment by MrMadguy64** [comment]
> 
> Usually not - but hdpmi does; not really recommended to use it, though.
> 
And what is recommended? Idle loop is easy solution, but I don't like it. Old hardware doesn't support power saving, so it doesn't matter, if idle loop is used there or not. But on newer hardware using something like HLT can reduce power consumption. Especially if CPU performance is exceeding.

Int 2Fh, 1680h can work on Windows, but it works a little bit differently and can cause even more problems.

I've heard about Int 28h, but, as I know, it doesn't do anything by default.

**Comment by Baron-von-Riedesel** [comment]
Well, you could do on your own what HDPMI does if a HLT is found in protected-mode: switch to real/v86-mode and execute the HLT there.
