### ISSUE TITLE
TESTOMF source and sample programs

### ISSUE THREAD

**Issue by cr1901** [Baron-von-Riedesel/HX#7]
Your [webpage](https://www.japheth.de/HX.html) for the HX DOS extender discusses the 32-bit MZ format.

>32bit DOS Apps in MZ Format
This format is also supported by HX and consists of
>* JMPPM32.OBJ to prepare app for 32bit protected mode execution
>* some helper functions in library JMPPM32.LIB
>* some libraries in OMF format for Win32 emulation (see below for more details)
>* Libc32.lib, a simple static C runtime library (OMF format)
>* **TestOMF**, a program to test 32bit MZ format support of various OMF linkers.
>* **Samples** in ASM and C

I didn't actually know MZ had a 32-bit format and am curious to learn more. It looks like (via GH search) neither the `TestOMF` binary or the samples are uploaded. Do you by any chance still have those and can upload them to this repo?

**Comment by Baron-von-Riedesel** [comment]
The "MZ format" has no special "32-bit" feature. It may contain "segment fixups", but these are hardly useful/needed for 32-bit protected-mode code, since such code is usually not "segmented".

The source for jmppm32.obj does still exist and most likely works, but in most cases it is easier to link the object moduleas as a PE binary and make the linker add the "loadpe.bin" stub.

**Comment by cr1901** [comment]
>In any case, support for the Win32 emulation in OMF format has been deprecated long ago.

Well I suppose my questions aren't relevant in that case. The context is that I have code for an OMF linker that I wrote a long time ago (for "fun"- I'm sure JWLINK is fine). And I wanted to possibly revive that code and test against your applications.


Might as well ask some follow-up q's while I'm here:

>but these are hardly useful/needed for 32-bit protected-mode code, since such code is usually not "segmented".

So when you say (on your website):

>- some popular OMF linkers have problems with 32bit segments > 64 kB.

You're referring to the tendency of tools like C compilers and assemblers to create multiple segments in the OMF files, even when you intend to create a flat mode executable? I.e. the linker's job is "concatenate all the segments into two 4GB segments- one for `CS`, one for `DS`- that point to the same base address"?

Additionally, what do you mean by:

>- applications cannot run in a true flat (=zero-based) memory model

By the time you jump into protected mode, won't you have the equivalent of a flat memory model? Won't `CS`/`DS` will resolve to the same physical start address after the jump to pmode?

**Comment by Baron-von-Riedesel** [comment]
Ok, I just uploaded the MZSUPP source code.
